### PR TITLE
Fix remove chapter heading

### LINKED ISSUE #20: Chapter number announcement in local language
I think this was determined to be an issue that needed to be dealt with by the HearThis team, technically, but I am putting it here because it is something that needs to be dealt with in order to make the UI ready for use by the average computer user. And in case there is a possibility that it could be dealt with by BK instead.
The word "chapter" is pulled from somewhere within HearThis. However, the speaker of the local language announces this in their own language. It isn't a problem in SAB because there is no word "Chapter" that appears, but in the video that is output from Bible Karaoke, "Chapter {1}" appears in English. 
I like the fact that the text appears at all, we just need to figure out how to make it easier for it to appear in the local language.

### PR DESCRIPTION
**Pull request by Hiro-Nakamura**
Now we detect if a given line in the HearThis xml is a chapter title.  If so, we ignore the text and audio that is associated with it.

Fix #20

### CODE REVIEW

File: public/cli/lib/commands/ffmpeg.js [hunk 1]
```diff
@@ -128,19 +130,20 @@ function checkAudioInput(done) {
...
                 wavFiles = files.filter((f) => f.indexOf(".wav") > -1),
                 audioFiles = [];
-
             // If this folder contains wave and mp3 files, then throw error
             if (mp3Files.length && wavFiles.length) {
                 return done(new Error("Conflicting audio types"));
             } else if (mp3Files.length) {
                 // can use glob format with .mp3 files
-                audioFiles = mp3Files;
+                audioFiles = mp3Files.filter((f)=>{ return Options.skipAudioFiles.indexOf(f) == -1; });
```
Comment (irahopkinson) [inline public/cli/lib/commands/ffmpeg.js]: Non-blocking: This can be simplified to `audioFiles = mp3Files.filter(f => Options.skipAudioFiles.indexOf(f) == -1);`. An implied return with no code block. Here and elsewhere.

File: public/cli/lib/commands/timing.js [hunk 2]
```diff
@@ -131,6 +134,10 @@ function checkInputExists(done) {
             return;
         }
         inputData = contents;
+
+        // since that worked, lets also scan this dir for all audio files
```
Comment (irahopkinson) [inline public/cli/lib/commands/timing.js]: Strictly speaking this changes what the `checkInputExists` method does. Either change the method name or put this functionality in its own method.

**Comment by megahirt** [comment]
This fixes #20

File: public/cli/lib/commands/ffmpeg.js (hunk 1 above)
Comment (Hiro-Nakamura) [reply public/cli/lib/commands/ffmpeg.js:138]: For changes like this, we should probably come up with a set of eslint rules for the project, and have some standard tool to auto correct these things.  We have recently moved to eslint + prettier for our projects.  Takes a lot of the decision making out of the programmers hands as it pertains to code formatting which should result in much more uniform code.  

On the flip side, it also means some code blocks look a bit more "janky" due to the prettier rules that we can't change.

Comment (Hiro-Nakamura) [reply public/cli/lib/commands/ffmpeg.js:138]: so for the moment, let's leave these as they are since they are valid javascript and wait for a common code linting solution.

Comment (irahopkinson) [reply public/cli/lib/commands/ffmpeg.js:138]: Sure, this was non-blocking anyway. We use prettier also so happy for you to add it to the project or make an issue for it.

File: public/cli/lib/commands/timing.js (hunk 2 above)
Comment (Hiro-Nakamura) [reply public/cli/lib/commands/timing.js]: ok fffffiiinnnnneeeee : I've fixed the n00b "just throw in some code that doesn't follow the function intention" error.

Comment (irahopkinson) [reply public/cli/lib/commands/timing.js]: Thanks.
